name: baseshop
description: BaseShop - E-commerce para vender cualquier producto
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Navigation
  go_router: ^14.2.0

  # HTTP
  dio: ^5.7.0

  # Dependency Injection
  get_it: ^7.7.0

  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2

  # Image Picker
  image_picker: ^1.0.0
  path_provider: ^2.1.0

  # Firebase
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1

  # Google Sign-In
  google_sign_in: ^6.2.1

  # UI
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1

  # Utils
  intl: any
  json_annotation: ^4.9.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
